### ISSUE TITLE
Block symmetry of coefficients not respected

### ISSUE THREAD

**Issue by jonasschneidercgg** [constructivegravity/construct#16]
When solving equations including #<lambda:2:1:2:2:{...}> and #<lambda:2:2:2:1:{...}>, these two should be treated as the same coefficient, but they are not.

**Comment by crazyphysicist** [comment]
I see, that is of course true due to the exchange symmetry in the coefficients. 
The solution is to introduce a standard order for blocks, i.e. the canonical coefficient order would be `#<lambda:2:1:2:2:{...}>`. Before the program identifies the different coefficients in the parsing step, it should bring the definition into the canonical order.

The best way for the canonical order is to first sort the first and third block (smaller one to the left). If they are equal then sort by the second and fourth block.

Will be included in the next update.
